name: 'Deploy to aws s3'
description: 'deploy static'
inputs:
  bucket:
    description: 'The s3 bucket name'
    required: true
  bucket-region:
    description: 'The s3 region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'the folder containing deployable files'
    required: true
runs: 
  using: 'node16'
  main: 'main.js'